# constants file

CONST_NAME_LENGTH = 100
CONST_DESC_LENGTH = 500
CONST_EMAIL_LENGTH = 100
CONST_USER_TYPE_LENGTH = 20
CONST_PRODUCT_ID_LENGTH = 32
CONST_PRODUCT_QUESTION_LENGTH = 200
CONST_PRODUCT_ANSWER_LENGTH = 300
CONST_USER_ADDRESS_LENGTH = 500
CONS_USER_ADDRESS_HOUSE_NAME_LENGTH = 30
CONS_USER_ADDRESS_LANDMARK_LENGTH = 50
CONST_USER_ADDRESS_TYPE_LENGTH = 20
CONST_CHECKOUT_ORDER_ID_LENGTH = 32
CONST_PRODUCT_ORDER_ID_LENGTH = 32
CONST_CHOICE_ORDER_STATUS_LENGTH = 20
CONST_LENGTH_PAYMENT_RAZORPAY_ID = 50
CONST_CHOICES_LENGTH_PAYMENT_CURRENCY = 10
CONST_SHIPPING_ADDRESS_LENGTH = 500

# choices
CONST_CHOICE_USER_TYPE_BUYER = 'buyer'
CONST_CHOICE_USER_TYPE_SELLER = 'seller'
CONST_CHOICE_USER_TYPE_ADMIN = 'admin'
CONST_CHOICES_USER_TYPE = (
    (CONST_CHOICE_USER_TYPE_BUYER, CONST_CHOICE_USER_TYPE_BUYER),
    (CONST_CHOICE_USER_TYPE_SELLER, CONST_CHOICE_USER_TYPE_SELLER),
    (CONST_CHOICE_USER_TYPE_ADMIN, CONST_CHOICE_USER_TYPE_ADMIN),
)
CONST_CHOICE_USER_ADDRESS_TYPE_HOME = 'home'
CONST_CHOICE_USER_ADDRESS_TYPE_WORK = 'work'
CONST_CHOICES_USER_ADDRESS_TYPE = (
    (CONST_CHOICE_USER_ADDRESS_TYPE_HOME, CONST_CHOICE_USER_ADDRESS_TYPE_HOME),
    (CONST_CHOICE_USER_ADDRESS_TYPE_WORK, CONST_CHOICE_USER_ADDRESS_TYPE_WORK),
)
CONST_CHOICE_ORDER_STATUS_PLACED = 'placed'
CONST_CHOICE_ORDER_STATUS_PAID = 'paid'
CONST_CHOICE_ORDER_STATUS_SHIPPED = 'shipped'
CONST_CHOICE_ORDER_STATUS_DELIVERED = 'delivered'
CONST_CHOICES_ORDER_STATUS = (
    (CONST_CHOICE_ORDER_STATUS_PLACED, CONST_CHOICE_ORDER_STATUS_PLACED),
    (CONST_CHOICE_ORDER_STATUS_PAID, CONST_CHOICE_ORDER_STATUS_PAID),
    (CONST_CHOICE_ORDER_STATUS_SHIPPED, CONST_CHOICE_ORDER_STATUS_SHIPPED),
    (CONST_CHOICE_ORDER_STATUS_DELIVERED, CONST_CHOICE_ORDER_STATUS_DELIVERED),
)
CONST_CHOICE_PAYMENT_CURRENCY_INR = 'INR'
CONST_CHOICES_PAYMENT_CURRENCY = (
    (CONST_CHOICE_PAYMENT_CURRENCY_INR, CONST_CHOICE_PAYMENT_CURRENCY_INR),
)

#templates
CONST_ERROR_MESSAGE_INCORRECT_OTP_KEY = 'inv_otp'
CONST_ERROR_MESSAGE_INCORRECT_OTP_VALUE = 'Entered OTP is incorrect.'
CONST_ERROR_MESSAGE_EMAIL_NOT_PROVIDED_KEY = 'no_email'
CONST_ERROR_MESSAGE_EMAIL_NOT_PROVIDED_VALUE = 'Email not provided.'
CONST_ERROR_MESSAGE_EMAIL_OR_OTP_NOT_PROVIDED_KEY = 'no_email_otp'
CONST_ERROR_MESSAGE_EMAIL_OR_OTP_NOT_PROVIDED_VALUE = 'Please provide user email and otp'
CONST_ERROR_MESSAGE_INVALID_USER_KEY = 'inv_user'
CONST_ERROR_MESSAGE_INVALID_USER_VALUE = 'User does not exists'
CONST_ERROR_MESSAGE_INVALID_ID_KEY = 'inv_id'
CONST_ERROR_MESSAGE_INVALID_ID_VALUE = 'Id provided does not exists'
CONST_ERROR_MESSAGE_ADDRESS_COUNT_MAX_KEY = 'max_address_count'
CONST_ERROR_MESSAGE_ADDRESS_COUNT_MAX_VALUE = 'You can save only 3 address at a time'
CONST_ERROR_MESSAGE_PERMISSION_DENIED_KEY = 'permission_denied'
CONST_ERROR_MESSAGE_PERMISSION_DENIED_VALUE = "You do not have permission to perform this action"

CONST_ERROR_MESSAGE_TEMPLATES = {}
CONST_ERROR_MESSAGE_TEMPLATES[CONST_ERROR_MESSAGE_INCORRECT_OTP_KEY] = CONST_ERROR_MESSAGE_INCORRECT_OTP_VALUE
CONST_ERROR_MESSAGE_TEMPLATES[CONST_ERROR_MESSAGE_EMAIL_NOT_PROVIDED_KEY] = CONST_ERROR_MESSAGE_EMAIL_NOT_PROVIDED_VALUE
CONST_ERROR_MESSAGE_TEMPLATES[CONST_ERROR_MESSAGE_EMAIL_OR_OTP_NOT_PROVIDED_KEY] = CONST_ERROR_MESSAGE_EMAIL_OR_OTP_NOT_PROVIDED_VALUE
CONST_ERROR_MESSAGE_TEMPLATES[CONST_ERROR_MESSAGE_INVALID_USER_KEY] = CONST_ERROR_MESSAGE_INVALID_USER_VALUE
CONST_ERROR_MESSAGE_TEMPLATES[CONST_ERROR_MESSAGE_INVALID_ID_KEY] = CONST_ERROR_MESSAGE_INVALID_ID_VALUE
CONST_ERROR_MESSAGE_TEMPLATES[CONST_ERROR_MESSAGE_ADDRESS_COUNT_MAX_KEY] = CONST_ERROR_MESSAGE_ADDRESS_COUNT_MAX_VALUE
CONST_ERROR_MESSAGE_TEMPLATES[CONST_ERROR_MESSAGE_PERMISSION_DENIED_KEY] = CONST_ERROR_MESSAGE_PERMISSION_DENIED_VALUE

#email template
CONST_EMAIL_SEND_OTP_SUBJECT = 'Ecommerce - One Time Password'
CONST_EMAIL_SEND_OTP_MESSAGE = 'Your one time password is {otp}'