# Generated by Django 2.2 on 2020-02-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whishlist',
            new_name='Wishlist',
        ),
        migrations.RenameModel(
            old_name='WhislistItem',
            new_name='WishlistItem',
        ),
    ]
