# Generated by Django 2.2 on 2020-02-02 06:32

import api.models.services
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200201_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={},
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'product')},
        ),
        migrations.AlterIndexTogether(
            name='wishlistitem',
            index_together=set(),
        ),
        migrations.CreateModel(
            name='OrderForSeller',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=api.models.services.now)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('gift_wrap', models.BooleanField(default=False)),
                ('checkout_order_id', models.CharField(max_length=32)),
                ('product_order_id', models.CharField(max_length=32)),
                ('shipping_address', models.TextField(max_length=500)),
                ('product_amount', models.PositiveIntegerField()),
                ('has_delivered', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Seller')),
            ],
            options={
                'unique_together': {('product', 'checkout_order_id')},
            },
        ),
    ]
