# Generated by Django 2.2 on 2020-02-02 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200202_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderforseller',
            old_name='product_amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='orderforseller',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
        ),
        migrations.AlterUniqueTogether(
            name='orderforseller',
            unique_together={('product', 'order')},
        ),
        migrations.RemoveField(
            model_name='orderforseller',
            name='checkout_order_id',
        ),
        migrations.RemoveField(
            model_name='orderforseller',
            name='product_order_id',
        ),
    ]
