# Generated by Django 2.2 on 2020-02-02 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200202_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderforseller',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
        ),
    ]
